version: '3.7'
services:
  mongo:
    build: mongo
    command: mongod --quiet --logpath /dev/null
    ports:
      - "27017:27017"
  server:
    build: server
    command: npm run server
    ports:
      - "3030:3030"
    depends_on:
      - mongo
  frontend:
    build: frontend
    command: npm run start
    ports:
      - "3000:3000"
    depends_on:
      - server