version: '3.7'
services:
  mongo:
    image: 'mongo'
    restart: 'always'
    environment:
      - 'MONGO_INITDB_ROOT_USERNAME=root'
      - 'MONGO_INITDB_ROOT_PASSWORD=root'
    volumes:
      - './mongo/data:/data/db'
    ports:
      - "27017:27017"
  server:
    build: server
    working_dir: /server
    command: npm run server
    volumes:
      - ./server:/server
    ports:
      - "3030:3030"
  frontend:
    build: ./frontend
    working_dir: /frontend
    command: npm run dev
    volumes:
      - ./frontend:/frontend
    ports:
      - "3000:3000"
volumes:
  mongo_data: